version: '3.8'

services:
  checkout:
    build:
      context: ./checkout-ff
      dockerfile: Dockerfile # Vamos criar este Dockerfile também
    # ports: # Remover/comentar mapeamento direto
    volumes:
      - ./checkout-ff:/app
      - /app/node_modules # Evita que node_modules local sobrescreva o do container
    environment:
      - NODE_ENV=development
      # Você precisará criar um arquivo .env em checkout-ff com SHARKPAY_SECRET_KEY
      # Ou adicionar a variável diretamente aqui:
      # - SHARKPAY_SECRET_KEY=sua_chave_aqui
    command: npm start
    restart: unless-stopped # Adicionado para reiniciar se cair

  store:
    build:
      context: ./ff-new
      dockerfile: Dockerfile # E este também
    # ports: # Remover/comentar mapeamento direto
    volumes:
      - ./ff-new:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: yarn dev # Usar yarn dev para desenvolvimento, reflete mudanças sem rebuild 
    restart: unless-stopped # Adicionado para reiniciar se cair

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Mapeia a porta 80 do host para a porta 80 do Nginx
      # - "443:443" # Descomente se for configurar HTTPS depois
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Monta a config do Nginx (read-only)
      # - ./certbot/conf:/etc/letsencrypt # Descomente para HTTPS com Let's Encrypt
      # - ./certbot/www:/var/www/certbot # Descomente para HTTPS com Let's Encrypt
    depends_on:
      - store
      - checkout
    restart: unless-stopped # Adicionado para reiniciar se cair 